spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/musicadb}
  mvc:
    cors:
      allowed-origins: http://localhost:4200
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

cors:
  allowed-origins: http://localhost:4200,http://localhost