spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://mongodb:27017/musicadb}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    cors:
      allowed-origins: http://localhost:4200,http://host.docker.internal:4200
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

cors:
  allowed-origins: http://localhost:4200,http://localhost,http://host.docker.internal:4200

logging:
  level:
    org.springframework: DEBUG