spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/musica_prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    org.springframework.data.mongodb: INFO